stages:
  - build
  - deploy

build:
  stage: build
  tags:
    - 152-run
  image: node:18
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - build
    expire_in: 1 hour
  only:
    - main

deploy:
  stage: deploy
  tags:
    - 152-run
  image: node:18
  before_script:
    - apt-get update && apt-get install -y sshpass
  script:
    - sshpass -p 'your_password' scp -o StrictHostKeyChecking=no -r build/* root@11.231.240.168:/var/www/html/
  only:
    - main
  dependencies:
    - build